apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    service: user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
      - name: user
        image: containerregistryrobots.azurecr.io/user:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/users"
        - name: REDIS_HOST
          value: "redis"
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi